# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProfileİnformationViewScreenModule.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_txtRegisterScreen(object):
    def setupUi(self, txtRegisterScreen):
        txtRegisterScreen.setObjectName("txtRegisterScreen")
        txtRegisterScreen.setWindowModality(QtCore.Qt.WindowModal)
        txtRegisterScreen.resize(400, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(txtRegisterScreen.sizePolicy().hasHeightForWidth())
        txtRegisterScreen.setSizePolicy(sizePolicy)
        txtRegisterScreen.setMinimumSize(QtCore.QSize(400, 500))
        txtRegisterScreen.setMaximumSize(QtCore.QSize(400, 500))
        txtRegisterScreen.setSizeIncrement(QtCore.QSize(400, 500))
        txtRegisterScreen.setBaseSize(QtCore.QSize(400, 500))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        txtRegisterScreen.setFont(font)
        txtRegisterScreen.setMouseTracking(True)
        txtRegisterScreen.setFocusPolicy(QtCore.Qt.ClickFocus)
        txtRegisterScreen.setStyleSheet("")
        txtRegisterScreen.setSizeGripEnabled(False)
        txtRegisterScreen.setModal(False)
        self.groupBox = QtWidgets.QGroupBox(txtRegisterScreen)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 361, 361))
        self.groupBox.setObjectName("groupBox")
        self.lbPasswordNumber = QtWidgets.QLabel(self.groupBox)
        self.lbPasswordNumber.setGeometry(QtCore.QRect(10, 150, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbPasswordNumber.setFont(font)
        self.lbPasswordNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbPasswordNumber.setObjectName("lbPasswordNumber")
        self.lbDateTime = QtWidgets.QLabel(self.groupBox)
        self.lbDateTime.setGeometry(QtCore.QRect(10, 200, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbDateTime.setFont(font)
        self.lbDateTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbDateTime.setObjectName("lbDateTime")
        self.lbName = QtWidgets.QLabel(self.groupBox)
        self.lbName.setGeometry(QtCore.QRect(10, 30, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbName.setFont(font)
        self.lbName.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbName.setObjectName("lbName")
        self.lbNameP = QtWidgets.QLabel(self.groupBox)
        self.lbNameP.setGeometry(QtCore.QRect(10, 90, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbNameP.setFont(font)
        self.lbNameP.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbNameP.setObjectName("lbNameP")
        self.lbAddress = QtWidgets.QLabel(self.groupBox)
        self.lbAddress.setGeometry(QtCore.QRect(10, 270, 51, 16))
        self.lbAddress.setMaximumSize(QtCore.QSize(1000, 1000))
        self.lbAddress.setSizeIncrement(QtCore.QSize(1000, 1000))
        self.lbAddress.setBaseSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbAddress.setFont(font)
        self.lbAddress.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbAddress.setObjectName("lbAddress")
        self.lbNameView = QtWidgets.QLabel(self.groupBox)
        self.lbNameView.setGeometry(QtCore.QRect(150, 30, 200, 20))
        self.lbNameView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbNameView.setText("")
        self.lbNameView.setObjectName("lbNameView")
        self.lbNamePView = QtWidgets.QLabel(self.groupBox)
        self.lbNamePView.setGeometry(QtCore.QRect(150, 90, 200, 20))
        self.lbNamePView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbNamePView.setText("")
        self.lbNamePView.setObjectName("lbNamePView")
        self.lbPasswordNumberView = QtWidgets.QLabel(self.groupBox)
        self.lbPasswordNumberView.setGeometry(QtCore.QRect(150, 150, 200, 20))
        self.lbPasswordNumberView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbPasswordNumberView.setText("")
        self.lbPasswordNumberView.setObjectName("lbPasswordNumberView")
        self.lbDateView = QtWidgets.QLabel(self.groupBox)
        self.lbDateView.setGeometry(QtCore.QRect(150, 200, 200, 20))
        self.lbDateView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbDateView.setText("")
        self.lbDateView.setObjectName("lbDateView")
        self.lbAddressView = QtWidgets.QLabel(self.groupBox)
        self.lbAddressView.setGeometry(QtCore.QRect(150, 270, 200, 71))
        self.lbAddressView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbAddressView.setText("")
        self.lbAddressView.setObjectName("lbAddressView")
        self.btnUpdate = QtWidgets.QPushButton(txtRegisterScreen)
        self.btnUpdate.setGeometry(QtCore.QRect(110, 400, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setObjectName("btnUpdate")

        self.retranslateUi(txtRegisterScreen)
        QtCore.QMetaObject.connectSlotsByName(txtRegisterScreen)

    def retranslateUi(self, txtRegisterScreen):
        _translate = QtCore.QCoreApplication.translate
        txtRegisterScreen.setWindowTitle(_translate("txtRegisterScreen", "UserProfileView"))
        self.groupBox.setTitle(_translate("txtRegisterScreen", "BİLGİLER"))
        self.lbPasswordNumber.setText(_translate("txtRegisterScreen", "ŞİFRE"))
        self.lbDateTime.setText(_translate("txtRegisterScreen", "DOĞUM TARİHİ"))
        self.lbName.setText(_translate("txtRegisterScreen", "ADI"))
        self.lbNameP.setText(_translate("txtRegisterScreen", "SOYADI"))
        self.lbAddress.setText(_translate("txtRegisterScreen", "ADRES"))
        self.btnUpdate.setText(_translate("txtRegisterScreen", "Tamam"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    txtRegisterScreen = QtWidgets.QDialog()
    ui = Ui_txtRegisterScreen()
    ui.setupUi(txtRegisterScreen)
    txtRegisterScreen.show()
    sys.exit(app.exec_())
