# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QuestionOperation.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import databaseOperation

class Ui_AddDeleteQuestion(object):
    id=''
    question=''

    def setupUi(self, AddDeleteQuestion):
        AddDeleteQuestion.setObjectName("AddDeleteQuestion")
        AddDeleteQuestion.resize(400, 500)
        AddDeleteQuestion.setMinimumSize(QtCore.QSize(400, 500))
        AddDeleteQuestion.setMaximumSize(QtCore.QSize(400, 500))
        self.lbAddID = QtWidgets.QLabel(AddDeleteQuestion)
        self.lbAddID.setGeometry(QtCore.QRect(20, 90, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbAddID.setFont(font)
        self.lbAddID.setObjectName("lbAddID")
        self.lbAddQuestion = QtWidgets.QLabel(AddDeleteQuestion)
        self.lbAddQuestion.setGeometry(QtCore.QRect(20, 130, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbAddQuestion.setFont(font)
        self.lbAddQuestion.setObjectName("lbAddQuestion")
        self.lbSearchID = QtWidgets.QLabel(AddDeleteQuestion)
        self.lbSearchID.setGeometry(QtCore.QRect(20, 280, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbSearchID.setFont(font)
        self.lbSearchID.setObjectName("lbSearchID")
        self.lbIDDeleteView = QtWidgets.QLabel(AddDeleteQuestion)
        self.lbIDDeleteView.setGeometry(QtCore.QRect(20, 330, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbIDDeleteView.setFont(font)
        self.lbIDDeleteView.setObjectName("lbIDDeleteView")
        self.txtAddID = QtWidgets.QLineEdit(AddDeleteQuestion)
        self.txtAddID.setGeometry(QtCore.QRect(100, 90, 251, 20))
        self.txtAddID.setText("")
        self.txtAddID.setMaxLength(3)
        self.txtAddID.setClearButtonEnabled(True)
        self.txtAddID.setObjectName("txtAddID")
        self.txtSearchID = QtWidgets.QLineEdit(AddDeleteQuestion)
        self.txtSearchID.setGeometry(QtCore.QRect(100, 280, 101, 20))
        self.txtSearchID.setMaxLength(3)
        self.txtSearchID.setClearButtonEnabled(True)
        self.txtSearchID.setObjectName("txtSearchID")
        self.btnAdd = QtWidgets.QPushButton(AddDeleteQuestion)
        self.btnAdd.setGeometry(QtCore.QRect(140, 190, 180, 30))
        self.btnAdd.setObjectName("btnAdd")
        self.btnDelete = QtWidgets.QPushButton(AddDeleteQuestion)
        self.btnDelete.setGeometry(QtCore.QRect(140, 400, 180, 30))
        self.btnDelete.setObjectName("btnDelete")
        self.lbAddNoFunction = QtWidgets.QLabel(AddDeleteQuestion)
        self.lbAddNoFunction.setGeometry(QtCore.QRect(20, 40, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbAddNoFunction.setFont(font)
        self.lbAddNoFunction.setObjectName("lbAddNoFunction")
        self.lbDeleteNoFunction = QtWidgets.QLabel(AddDeleteQuestion)
        self.lbDeleteNoFunction.setGeometry(QtCore.QRect(20, 240, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbDeleteNoFunction.setFont(font)
        self.lbDeleteNoFunction.setObjectName("lbDeleteNoFunction")
        self.btnSearch = QtWidgets.QPushButton(AddDeleteQuestion)
        self.btnSearch.setGeometry(QtCore.QRect(210, 280, 141, 20))
        self.btnSearch.setObjectName("btnSearch")
        self.lbIDView = QtWidgets.QLabel(AddDeleteQuestion)
        self.lbIDView.setGeometry(QtCore.QRect(100, 330, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbIDView.setFont(font)
        self.lbIDView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbIDView.setText("")
        self.lbIDView.setObjectName("lbIDView")
        self.lbQuestionView = QtWidgets.QLabel(AddDeleteQuestion)
        self.lbQuestionView.setGeometry(QtCore.QRect(100, 360, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbQuestionView.setFont(font)
        self.lbQuestionView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbQuestionView.setText("")
        self.lbQuestionView.setObjectName("lbQuestionView")
        self.lbQuestionDeleteView = QtWidgets.QLabel(AddDeleteQuestion)
        self.lbQuestionDeleteView.setGeometry(QtCore.QRect(20, 360, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbQuestionDeleteView.setFont(font)
        self.lbQuestionDeleteView.setObjectName("lbQuestionDeleteView")
        self.txtAddQuestion = QtWidgets.QTextEdit(AddDeleteQuestion)
        self.txtAddQuestion.setGeometry(QtCore.QRect(100, 130, 251, 51))
        self.txtAddQuestion.setObjectName("txtAddQuestion")

        self.retranslateUi(AddDeleteQuestion)
        QtCore.QMetaObject.connectSlotsByName(AddDeleteQuestion)
        self.btnAdd.clicked.connect(self.addQuestion)
        self.btnSearch.clicked.connect(self.getQuestion)
        self.btnDelete.clicked.connect(self.deletQuestion)

    def retranslateUi(self, AddDeleteQuestion):
        _translate = QtCore.QCoreApplication.translate
        AddDeleteQuestion.setWindowTitle(_translate("AddDeleteQuestion", "Soru Ekleme ve Çıkarma "))
        self.lbAddID.setText(_translate("AddDeleteQuestion", "ID"))
        self.lbAddQuestion.setText(_translate("AddDeleteQuestion", "Soru"))
        self.lbSearchID.setText(_translate("AddDeleteQuestion", "ID"))
        self.lbIDDeleteView.setText(_translate("AddDeleteQuestion", "ID"))
        self.btnAdd.setText(_translate("AddDeleteQuestion", "Ekle"))
        self.btnDelete.setText(_translate("AddDeleteQuestion", "Sil"))
        self.lbAddNoFunction.setText(_translate("AddDeleteQuestion", "Ekleme"))
        self.lbDeleteNoFunction.setText(_translate("AddDeleteQuestion", "Silme"))
        self.btnSearch.setText(_translate("AddDeleteQuestion", "Ara"))
        self.lbQuestionDeleteView.setText(_translate("AddDeleteQuestion", "Soru"))

    def addQuestion(self):
        questionOpr=databaseOperation.QuestionOperations('database.db')
        self.id=self.txtAddID.text()
        self.question=self.txtAddQuestion.toPlainText()
        if(questionOpr.addQuestion(self.id,self.question)):
            print("Soru Eklendi...")

    def getQuestion(self):
        questionOpr=databaseOperation.QuestionOperations('database.db')
        self.id=(int)(self.txtSearchID.text())
        question=questionOpr.getQuestion(self.id)
        if(len(question)!=0):
            self.lbQuestionView.setText((str)(question[0][1]))
            self.lbIDView.setText((str)(question[0][0]))
        else:
            self.lbQuestionView.setText('')
            self.lbIDView.setText('')

    def deletQuestion(self):
        questionOpr=databaseOperation.QuestionOperations('database.db')
        self.id=(int)(self.txtSearchID.text())
        if(questionOpr.dropQuestion(self.id)):
            print("Başarıyla silindi...")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddDeleteQuestion = QtWidgets.QWidget()
    ui = Ui_AddDeleteQuestion()
    ui.setupUi(AddDeleteQuestion)
    AddDeleteQuestion.show()
    sys.exit(app.exec_())
